"---------------------------------------------------------------------------
" callmekohei's .vimrc
"---------------------------------------------------------------------------

"---------------------------------------------------------------------------

" profile start profile.txt
" profile file ~/.vim/rc/*
" profile func dein#*



if &compatible
    set nocompatible
endif

if executable('brew')
    if has('nvim')
        :silent let s:brewHome = systemlist('brew --prefix')
        let g:python_host_prog  = s:brewHome[0].'/bin/python2'
        let g:python3_host_prog = s:brewHome[0].'/bin/python3'
    endif
endif

execute 'source' '~/dotfiles/vim/rc/dein.rc.vim'
execute 'source' '~/dotfiles/vim/rc/common.vim'
execute 'source' '~/dotfiles/vim/rc/mappings.rc.vim'
execute 'source' '~/dotfiles/vim/rc/local.vim'
