"---------------------------------------------------------------------------
" callmekohei's .vimrc
"---------------------------------------------------------------------------
if &compatible
    set nocompatible
endif
execute 'source' '~/dotfiles/vim/rc/init.rc.vim'
execute 'source' '~/dotfiles/vim/rc/dein.rc.vim'
execute 'source' '~/dotfiles/vim/rc/encoding.rc.vim'
execute 'source' '~/dotfiles/vim/rc/options.rc.vim'
execute 'source' '~/dotfiles/vim/rc/mappings.rc.vim'
execute 'source' '~/dotfiles/vim/rc/local.vim'
if has('nvim')
    execute 'source' '~/dotfiles/vim/rc/neovim.rc.vim'
endif
