#---------------------------------------------------------------------------
# Auto complete
#

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
    augroup Foo
        autocmd!
    augroup END


    call deoplete#custom#option({
    \ 'auto_complete_delay': 0,
    \ 'ignore_case': v:true,
    \ })

    call deoplete#custom#source('_',
    \ 'converters', ['remove_overlap'])

    "---------------------------------
    " Dictionary
    "---------------------------------

    if &filetype == 'dependencies'
        setlocal dictionary+=~/tmp/mydictionary/foo_dictionary
    endif

    " Note: You must call (deoplete#custom#source) before using deoplete.
    call deoplete#enable()
'''

[[plugins]]
repo = 'callmekohei/deoplete-fsharp'
build = 'bash install.bash'
on_ft = 'fsharp'





[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
    let g:deoplete#sources#jedi#python_path = '/usr/local/bin/python'
'''

#---------------------------------------------------------------------------
# Markdown
#
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['markdown','toml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source='''
    let g:vim_markdown_conceal = 0
    let g:vim_markdown_toml_frontmatter = 1
    let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'
hook_source = '''
    source ~/dotfiles/vim/rc/dein/plugins/previm.rc.vim
'''

#---------------------------------------------------------------------------
# Others
#

# [[plugins]]
# repo = 'vobornik/vim-mql4'

# [[plugins]]
# repo = 'Shougo/neco-syntax'
# on_ft = 'mql4'
# hook_source = '''
# 	let g:quickrun_config.mql4 = {
#         \  'exec': [ '%c %o %s:p:t' ]
#         \ ,'command':'bash'
#         \ ,'cmdopt' :'$HOME/tmp/quickrunMQL/quickrunMQL.bash'
#     \}
# '''

# let g:quickrun_config.less = {
#     \  'exec'   :  [ '%c -clean-css %s:p:r.less' ]
#     \ ,'command':  'lessc'
# \}
