[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'fsharp/vim-fsharp'
# on_ft = 'fsharp'
# build = 'make fsautocomplete'

# [[plugins]]
# repo = 'ervandew/supertab'
# on_ft = 'fsharp'

# on_if が効いてない気がする ( 2018/06/07 )
# [[plugins]]
# repo  = 'roxma/vim-hug-neovim-rpc'
# on_if = '!has("nvim")'
#
# [[plugins]]
# repo  = 'roxma/nvim-yarp'
# on_if = '!has("nvim")'
#
# [[plugins]]
# repo  = 'callmekohei/tigaDebugger'
# on_if = '!has("nvim")'

[[plugins]]
repo     = 'junegunn/fzf.vim'
build    = './install --all'
hook_add = 'source ~/dotfiles/vim/rc/dein/plugins/fzf.rc.vim'

[[plugins]]
repo = 'romainl/Apprentice'
hook_add = '''
    function! MyHighlights() abort
        highlight Comment ctermfg=245 guifg=#8a8a8a
    endfunction

    autocmd MyAutoCmd ColorScheme * call MyHighlights()
'''





[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    if !exists('g:tcomment_types')
        let g:tcomment_types = {}
    endif
    let g:tcomment_types['fsharp'] = '// %s'
    let g:tcomment_types['mql4'] = '// %s'
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
    xmap ga <Plug>(EasyAlign)
    nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_start_level = 2
    let g:indent_guides_guide_size  = 1
    let g:indent_guides_auto_colors = 0
    autocmd MyAutoCmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#3A3C43 ctermbg=0
    autocmd MyAutoCmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#3A3C43 ctermbg=0
'''

[[plugins]]
repo     = 'thinca/vim-quickrun'
depends  = ['Shougo/vimproc.vim']
hook_add = 'source ~/dotfiles/vim/rc/dein/plugins/quickrun.rc.vim'

[[plugins]]
repo      = 'Shougo/vimproc.vim'
build     = 'make'
on_source = ['vim-quickrun']

[[plugins]]
repo = 'thinca/vim-partedit'
hook_add = '''
    let g:partedit#opener = 'vsp'
    let g:partedit#filetype = 'vim'
'''

[[plugins]]
repo = 'kana/vim-textobj-user'



