# ===========================================================================
#  FILE    : dein_lazy.toml
#  AUTHOR  : callmekohei <callmekohei at gmail.com>
# ===========================================================================


#----------------------------------------------------------
# F#
#----------------------------------------------------------

[[plugins]]
repo = 'callmekohei/deoplete-fsharp'
build = 'bash install.bash'
on_ft = 'fsharp'
hook_add = '''
    augroup fsharp

        let s:err     = '%f(%l\,%c):\ %m'
        let s:blank01 = '%-G %.%#'
        let s:blank02 = '%-G'
        let s:invalid = '%-G%[%^/]%.%#'

        let s:lst = [
            \   s:err
            \ , s:blank01
            \ , s:blank02
            \ , s:invalid
            \ ]

        autocmd!
        autocmd FileType fsharp let &errorformat = join( s:lst , ',' )
        autocmd bufnewfile,bufread *.fsx  execute ":QuickRun fsharpCheck"
        autocmd bufwritepost       *.fsx  execute ":QuickRun fsharpCheck"
    augroup end
'''

[[plugins]]
repo = 'callmekohei/tigaDebugger'
on_ft = 'fsharp'


#----------------------------------------------------------
# Markdown browser
#----------------------------------------------------------

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add='''
    let g:vim_markdown_conceal = 0
    let g:vim_markdown_toml_frontmatter = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'
hook_add = '''
    let g:previm_open_cmd = 'open -a Firefox'
    let g:previm_disable_default_css = 1
    let g:previm_custom_css_path     = '/Users/callmekohei/.config/nvim/dein/repos/github.com/kannokanno/previm/preview/css/github.css'

    augroup PrevimSettings
      autocmd!
      autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
    augroup END

    let s:githubCss = "/Users/callmekohei/.config/nvim/dein/repos/github.com/kannokanno/previm/preview/css/github.css"
    let s:address   = "https://gist.githubusercontent.com/andyferra/2554919/raw/10ce87fe71b23216e3075d5648b8b9e56f7758e1/github.css"
    let s:folder    = "/Users/callmekohei/.config/nvim/dein/repos/github.com/kannokanno/previm/preview/css"

    if isdirectory(s:folder)
        if !filereadable(s:githubCss)
          execute '!wget' s:address '-P' s:folder
        endif
    endif
'''


#----------------------------------------------------------
# Python
#----------------------------------------------------------

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
    let g:deoplete#sources#jedi#python_path = '/usr/local/bin/python'
'''



#----------------------------------------------------------
# Others
#----------------------------------------------------------

# [[plugins]]
# repo = 'vobornik/vim-mql4'

# [[plugins]]
# repo = 'Shougo/neco-syntax'
# on_ft = 'mql4'
# hook_add = '''
# 	let g:quickrun_config.mql4 = {
#         \  'exec': [ '%c %o %s:p:t' ]
#         \ ,'command':'bash'
#         \ ,'cmdopt' :'$HOME/tmp/quickrunMQL/quickrunMQL.bash'
#     \}
# '''

# let g:quickrun_config.less = {
#     \  'exec'   :  [ '%c -clean-css %s:p:r.less' ]
#     \ ,'command':  'lessc'
# \}
