[[plugins]]
repo = 'callmekohei/deoplete-fsharp'
build = 'bash install.bash'
on_ft = 'fsharp'

[[plugins]]
repo = 'callmekohei/tigaDebugger'
on_ft = 'fsharp'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source='''
    source ~/dotfiles/vim/plugins/vim-markdown.vim
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'
hook_source = '''
    source ~/dotfiles/vim/plugins/previmrc.vim
'''


#----------------------------------------------------------
# Python
#----------------------------------------------------------

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
    source ~/dotfiles/vim/plugins/deoplete-jedirc.vim
'''



#----------------------------------------------------------
# Others
#----------------------------------------------------------

# [[plugins]]
# repo = 'vobornik/vim-mql4'

# [[plugins]]
# repo = 'Shougo/neco-syntax'
# on_ft = 'mql4'
# hook_source = '''
# 	let g:quickrun_config.mql4 = {
#         \  'exec': [ '%c %o %s:p:t' ]
#         \ ,'command':'bash'
#         \ ,'cmdopt' :'$HOME/tmp/quickrunMQL/quickrunMQL.bash'
#     \}
# '''

# let g:quickrun_config.less = {
#     \  'exec'   :  [ '%c -clean-css %s:p:r.less' ]
#     \ ,'command':  'lessc'
# \}
