[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'romainl/Apprentice'
hook_add = '''
    function! MyHighlights() abort
        highlight Comment ctermfg=245
    endfunction

    augroup MyColors
        autocmd!
        autocmd ColorScheme * call MyHighlights()
    augroup END
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    "source ~/dotfiles/vim/plugins/tcomment_vimrc.vim
    if !exists('g:tcomment_types')
        let g:tcomment_types = {}
    endif
    let g:tcomment_types['fsharp'] = '// %s'
    let g:tcomment_types['mql4'] = '// %s'
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
    xmap ga <Plug>(EasyAlign)
    nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    augroup MyIndent
        autocmd!
        let g:indent_guides_enable_on_vim_startup = 1
        let g:indent_guides_start_level = 2
        let g:indent_guides_guide_size = 1
        let g:indent_guides_auto_colors = 0
        autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=black ctermbg=0
        autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=black ctermbg=0
    augroup END
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo     = 'thinca/vim-quickrun'
depends  = ['Shougo/vimproc.vim']
hook_add = '''

    let g:quickrun_config = {}

    let g:quickrun_config._ = {
        \  'runner'                          : 'vimproc'
        \ ,'runner/vimproc/updatetime'       : 60
        \ ,'hook/time/enable'                : 1
        \ ,'hook/time/format'                : "\n*** time : %g s ***"
        \ ,'hook/time/dest'                  : ''
        \ ,"outputter/buffer/split"          : 'vertical'
        \ ,'outputter/buffer/close_on_empty' : 1
    \}

    let g:quickrun_config.bashCheck = {
        \  'exec'                            : [ '%c -n %s:p:r.bash' ]
        \ ,'command'                         : 'bash'
        \ ,'hook/time/enable'                : 0
        \ ,"outputter/buffer/close_on_empty" : 1
        \ ,"outputter"                       : 'quickfix'
        \ ,'outputter/buffer/split'          : ':set splitblow',
    \}

    let g:quickrun_config.fsharp = {
        \  'command'                         : 'fsharpi --readline-'
        \ ,'runner'                          : 'concurrent_process'
        \ ,'runner/concurrent_process/load'  : '#load "%S";;'
        \ ,'runner/concurrent_process/prompt': '> '
    \}

    let g:quickrun_config.fsharpCheck = {
        \  'command'                         : 'fsharpi --readline-'
        \ ,'runner'                          : 'concurrent_process'
        \ ,'runner/concurrent_process/load'  : '#load "%S";;'
        \ ,'runner/concurrent_process/prompt': '> '
        \ ,'hook/time/enable'                : 0
        \ ,"outputter/buffer/close_on_empty" : 1
        \ ,"outputter"                       : 'quickfix'
        \ ,'outputter/buffer/split'          : ':set splitblow',
    \}

    let g:quickrun_config.fsharpi = {
        \  'exec'   :  [ '%c %s:p:r.fsx' ]
        \ ,'command':  'fsharpi'
        \ ,'args'   :  '%{input("args> ")}'
    \}

    let g:quickrun_config.python = {
        \ 'command': 'python3'
    \}

    let g:quickrun_config.sh = {
        \ 'command': 'bash'
    \}
'''

[[plugins]]
repo = 'thinca/vim-partedit'
hook_add = '''
    let g:partedit#opener = 'vsp'
    let g:partedit#filetype = 'vim'
'''

[[plugins]]
repo = 'kana/vim-textobj-user'
