[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
    source ~/dotfiles/vim/plugins/vim-easy-alignrc.vim
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    source ~/dotfiles/vim/plugins/deopleterc.vim
'''

[[plugins]]
repo = 'romainl/Apprentice'
hook_add = '''
    source ~/dotfiles/vim/plugins/Apprenticerc.vim
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
    source ~/dotfiles/vim/plugins/tcomment_vimrc.vim
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    source ~/dotfiles/vim/plugins/vim-indent-guidesrc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo     = 'thinca/vim-quickrun'
depends  = ['Shougo/vimproc.vim']
hook_add = '''
    source ~/dotfiles/vim/plugins/quickrunrc.vim
'''
