scriptencoding utf-8
"---------------------------------------------------------------------------
" カラー設定:
"
" Don't override colorscheme.
if !exists('g:colors_name')
    colorscheme default
endif

"---------------------------------------------------------------------------
" フォント設定:
"
let s:fontname = 'Droid Sans Mono for Powerline Nerd Font Complete'
let &guifont = s:fontname.":h14"
set linespace=3

"---------------------------------------------------------------------------
" ウインドウに関する設定:
"
" ウインドウの幅
set columns=80
" ウインドウの高さ
set lines=30
" コマンドラインの高さ(GUI使用時)
set cmdheight=2

"---------------------------------------------------------------------------
" 表示に関する設定:
"
" Hide toolbar and menus.
set guioptions-=Tt
set guioptions-=m
" Scrollbar is always off.
set guioptions-=rL
" Not guitablabel.
set guioptions-=e
" Confirm without window.
set guioptions+=c
" Don't flick cursor.
set guicursor&
set guicursor+=a:blinkon0
