if &compatible
  set nocompatible
endif

" encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-boms,utf-8,euc-jp,cp932
set fileformats=unix,dos,mac
if !has('gui_running') && &encoding != 'utf-8'
  set termencoding=utf-8
endif

"vimrc's scriptencoding
scriptencoding utf-8

" create autocmd group
augroup MyAutoCmd
  autocmd!
augroup END

" Use English interface.
language message C

execute 'source' '~/dotfiles/vim/rc/02-plugin.vim'
execute 'source' '~/dotfiles/vim/rc/03-option.vim'
execute 'source' '~/dotfiles/vim/rc/04-mapping.vim'
execute 'source' '~/dotfiles/vim/rc/05-filetype.vim'

if has('nvim')
  execute 'source' '~/dotfiles/vim/rc/11-neovim.vim'
endif

if has('mac')
  execute 'source' '~/dotfiles/vim/rc/12-macosx.vim'
endif

if !filereadable( '~/dotfiles/vim/rc/91-local.vim' )
  execute 'source' '~/dotfiles/vim/rc/91-local.vim'
endif


