scriptencoding utf-8

if &compatible
    set nocompatible
endif

" Use English interface.
language message C

execute 'source' '~/dotfiles/vim/rc/01-encodeing.vim'
execute 'source' '~/dotfiles/vim/rc/02-plugin.vim'
execute 'source' '~/dotfiles/vim/rc/03-option.vim'
execute 'source' '~/dotfiles/vim/rc/04-mapping.vim'
execute 'source' '~/dotfiles/vim/rc/05-filetype.vim'

if has('nvim')
    execute 'source' '~/dotfiles/vim/rc/11-neovim.vim'
endif

if has('mac')
    execute 'source' '~/dotfiles/vim/rc/12-macosx.vim'
endif

if !filereadable( '~/dotfiles/vim/rc/91-local.vim' )
    execute 'source' '~/dotfiles/vim/rc/91-local.vim'
endif
