### kohei's bashrc

### Environment
export EDITOR=vim
export LANG=ja_JP.UTF-8

### Folder, File color
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

### Prompt
PS1='\n\w\n\$ '
export PS1

### Alias
alias ls='ls -F'
alias ll='ls -a -l'
alias cd..='cd ..'

### import env. settings
if [ "$(uname)" == 'Darwin' ]; then
  source $HOME/dotfiles/bash/bashrc_osx
elif [ "$(expr substr $(uname -s) 1 10)" == 'MINGW64_NT' ]; then
  source /y/dotfiles/bash/bashrc_gitbash
else
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
fi

### Ariawase cmd ( VBA )
alias decombine='cscript vbac.wsf decombine'
alias combine='cscript vbac.wsf combine'
alias clear='cscript vbac.wsf clear'


### rust

export CARGO_HOME="$HOME/.cargo"
export PATH="$CARGO_HOME/bin:$PATH"
